<a href="https://colab.research.google.com/github/HarithaSuneesh/csv.py/blob/main/5thproject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### READING DATA

In [1]:
import pandas as pd
df=pd.read_csv("https://drive.google.com/uc?export=download&id=17t7BMoeh-EDKKEGy5uLRyA_FRtcUB7Gd")
df

            Date     Price      Open      High       Low     Vol. Change %
0     24-03-2024  67,211.9  64,036.5  67,587.8  63,812.9   65.59K    4.96%
1     23-03-2024  64,037.8  63,785.6  65,972.4  63,074.9   35.11K    0.40%
2     22-03-2024  63,785.5  65,501.5  66,633.3  62,328.3   72.43K   -2.62%
3     21-03-2024  65,503.8  67,860.0  68,161.7  64,616.1   75.26K   -3.46%
4     20-03-2024  67,854.0  62,046.8  68,029.5  60,850.9  133.53K    9.35%
...          ...       ...       ...       ...       ...      ...      ...
4994  22-07-2010       0.1       0.1       0.1       0.1    2.16K    0.00%
4995  21-07-2010       0.1       0.1       0.1       0.1    0.58K    0.00%
4996  20-07-2010       0.1       0.1       0.1       0.1    0.26K    0.00%
4997  19-07-2010       0.1       0.1       0.1       0.1    0.57K    0.00%
4998  18-07-2010       0.1       0.0       0.1       0.1    0.08K    0.00%

[4999 rows x 7 columns]

### DATA TYPES

In [2]:
print(df.dtypes)
print(df.head())

Date        object
Price       object
Open        object
High        object
Low         object
Vol.        object
Change %    object
dtype: object
         Date     Price      Open      High       Low     Vol. Change %
0  24-03-2024  67,211.9  64,036.5  67,587.8  63,812.9   65.59K    4.96%
1  23-03-2024  64,037.8  63,785.6  65,972.4  63,074.9   35.11K    0.40%
2  22-03-2024  63,785.5  65,501.5  66,633.3  62,328.3   72.43K   -2.62%
3  21-03-2024  65,503.8  67,860.0  68,161.7  64,616.1   75.26K   -3.46%
4  20-03-2024  67,854.0  62,046.8  68,029.5  60,850.9  133.53K    9.35%

### SORTING BY DATE

In [3]:
import pandas as pd

# 1. Convert the Date column from text (object) to actual datetime objects
df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')

# 2. Sort by the Date column from oldest to newest
df_sorted = df.sort_values(by='Date', ascending=True)

# 3. Reset the index so the row numbers start over from 0
df_sorted = df_sorted.reset_index(drop=True)

# View your beautifully sorted historical data
print(df_sorted.head())
# Save to a new CSV file
df_sorted.to_csv('Bitcoin_Historical_Data_Sorted.csv', index=False)

        Date Price Open High  Low   Vol. Change %
0 2010-07-18   0.1  0.0  0.1  0.1  0.08K    0.00%
1 2010-07-19   0.1  0.1  0.1  0.1  0.57K    0.00%
2 2010-07-20   0.1  0.1  0.1  0.1  0.26K    0.00%
3 2010-07-21   0.1  0.1  0.1  0.1  0.58K    0.00%
4 2010-07-22   0.1  0.1  0.1  0.1  2.16K    0.00%

### SAVE AS CSV FILE

In [4]:
import pandas as pd
df=pd.read_csv("Bitcoin_Historical_Data_Sorted.csv")
df

            Date     Price      Open      High       Low     Vol. Change %
0     2010-07-18       0.1       0.0       0.1       0.1    0.08K    0.00%
1     2010-07-19       0.1       0.1       0.1       0.1    0.57K    0.00%
2     2010-07-20       0.1       0.1       0.1       0.1    0.26K    0.00%
3     2010-07-21       0.1       0.1       0.1       0.1    0.58K    0.00%
4     2010-07-22       0.1       0.1       0.1       0.1    2.16K    0.00%
...          ...       ...       ...       ...       ...      ...      ...
4994  2024-03-20  67,854.0  62,046.8  68,029.5  60,850.9  133.53K    9.35%
4995  2024-03-21  65,503.8  67,860.0  68,161.7  64,616.1   75.26K   -3.46%
4996  2024-03-22  63,785.5  65,501.5  66,633.3  62,328.3   72.43K   -2.62%
4997  2024-03-23  64,037.8  63,785.6  65,972.4  63,074.9   35.11K    0.40%
4998  2024-03-24  67,211.9  64,036.5  67,587.8  63,812.9   65.59K    4.96%

[4999 rows x 7 columns]

### PICKLING THE CSV FILE

In [5]:
# Save as a pickle file to preserve data types perfectly
df_sorted.to_pickle('Bitcoin_Historical_Data_Sorted.pkl')

# To load it back in your next script:
# df_sorted = pd.read_pickle('Bitcoin_Historical_Data_Sorted.pkl')

### HANDLING MISSING VALUES

In [6]:
df.isnull().sum()

Date        0
Price       0
Open        0
High        0
Low         0
Vol.        6
Change %    0
dtype: int64

### CONVERTING VOLUME COLUMN INTO NUMBERS

In [7]:
import numpy as np
import pandas as pd

def convert_volume(val):
    # Check for empty values or the literal dash placeholder
    if pd.isna(val) or val == '-':
        return np.nan

    val = str(val).strip().upper()
    if 'K' in val:
        return float(val.replace('K', '')) * 1_000
    elif 'M' in val:
        return float(val.replace('M', '')) * 1_000_000
    elif 'B' in val:
        return float(val.replace('B', '')) * 1_000_000_000

    return float(val)

# Apply the transformation to the 'Vol.' column
df['Vol.'] = df['Vol.'].apply(convert_volume)

# Now, fill the missing values with the median of the converted numeric 'Vol.' column
df['Vol.'] = df['Vol.'].fillna(df['Vol.'].median())
df

            Date     Price      Open      High       Low      Vol. Change %
0     2010-07-18       0.1       0.0       0.1       0.1      80.0    0.00%
1     2010-07-19       0.1       0.1       0.1       0.1     570.0    0.00%
2     2010-07-20       0.1       0.1       0.1       0.1     260.0    0.00%
3     2010-07-21       0.1       0.1       0.1       0.1     580.0    0.00%
4     2010-07-22       0.1       0.1       0.1       0.1    2160.0    0.00%
...          ...       ...       ...       ...       ...       ...      ...
4994  2024-03-20  67,854.0  62,046.8  68,029.5  60,850.9  133530.0    9.35%
4995  2024-03-21  65,503.8  67,860.0  68,161.7  64,616.1   75260.0   -3.46%
4996  2024-03-22  63,785.5  65,501.5  66,633.3  62,328.3   72430.0   -2.62%
4997  2024-03-23  64,037.8  63,785.6  65,972.4  63,074.9   35110.0    0.40%
4998  2024-03-24  67,211.9  64,036.5  67,587.8  63,812.9   65590.0    4.96%

[4999 rows x 7 columns]

In [8]:
df['Vol.'].sum()

np.float64(61798025320.0)

In [9]:
df['Vol.'] = df['Vol.'].ffill()
df['Vol.'].sum()

np.float64(61798025320.0)

In [10]:
df['Vol.'].isnull().sum()

np.int64(0)

In [11]:

df

            Date     Price      Open      High       Low      Vol. Change %
0     2010-07-18       0.1       0.0       0.1       0.1      80.0    0.00%
1     2010-07-19       0.1       0.1       0.1       0.1     570.0    0.00%
2     2010-07-20       0.1       0.1       0.1       0.1     260.0    0.00%
3     2010-07-21       0.1       0.1       0.1       0.1     580.0    0.00%
4     2010-07-22       0.1       0.1       0.1       0.1    2160.0    0.00%
...          ...       ...       ...       ...       ...       ...      ...
4994  2024-03-20  67,854.0  62,046.8  68,029.5  60,850.9  133530.0    9.35%
4995  2024-03-21  65,503.8  67,860.0  68,161.7  64,616.1   75260.0   -3.46%
4996  2024-03-22  63,785.5  65,501.5  66,633.3  62,328.3   72430.0   -2.62%
4997  2024-03-23  64,037.8  63,785.6  65,972.4  63,074.9   35110.0    0.40%
4998  2024-03-24  67,211.9  64,036.5  67,587.8  63,812.9   65590.0    4.96%

[4999 rows x 7 columns]

### Scale features using MinMaxScaler

In [12]:
from sklearn.preprocessing import MinMaxScaler

# Convert 'Price' column to numeric, handling commas
df['Price'] = df['Price'].astype(str).str.replace(',', '', regex=False).astype(float)

scaler = MinMaxScaler(feature_range=(0, 1))
# Reshape is required because the scaler expects a 2D array shape
scaled_price = scaler.fit_transform(df['Price'].values.reshape(-1, 1))
df

            Date    Price      Open      High       Low      Vol. Change %
0     2010-07-18      0.1       0.0       0.1       0.1      80.0    0.00%
1     2010-07-19      0.1       0.1       0.1       0.1     570.0    0.00%
2     2010-07-20      0.1       0.1       0.1       0.1     260.0    0.00%
3     2010-07-21      0.1       0.1       0.1       0.1     580.0    0.00%
4     2010-07-22      0.1       0.1       0.1       0.1    2160.0    0.00%
...          ...      ...       ...       ...       ...       ...      ...
4994  2024-03-20  67854.0  62,046.8  68,029.5  60,850.9  133530.0    9.35%
4995  2024-03-21  65503.8  67,860.0  68,161.7  64,616.1   75260.0   -3.46%
4996  2024-03-22  63785.5  65,501.5  66,633.3  62,328.3   72430.0   -2.62%
4997  2024-03-23  64037.8  63,785.6  65,972.4  63,074.9   35110.0    0.40%
4998  2024-03-24  67211.9  64,036.5  67,587.8  63,812.9   65590.0    4.96%

[4999 rows x 7 columns]

### Train-test split using time-based split

In [13]:
import pandas as pd

# Ensure df is loaded in case previous cells were not run or kernel was reset
df = pd.read_csv("Bitcoin_Historical_Data_Sorted.csv")

# Define your split ratio (e.g., 80% for training)
train_ratio = 0.80
split_idx = int(len(df) * train_ratio)

# 3. Slice the data chronologically without shuffling
train_df = df.iloc[:split_idx]
# The remaining 20% goes to testing
test_df = df.iloc[split_idx:]

# Quick verification check
print(f"Total records: {len(df)}")
print(f"Train set:     {len(train_df)} rows (from {train_df.index.min()} to {train_df.index.max()})")
print(f"Test set:      {len(test_df)} rows (from {test_df.index.min()} to {test_df.index.max()})")

Total records: 4999
Train set:     3999 rows (from 0 to 3998)
Test set:      1000 rows (from 3999 to 4998)

### Selecting features and target

In [14]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# 1. Select features and target (e.g., using 'Price' to predict the next day's 'Price')
# Adjust column names based on your actual CSV
features = ['Price']  # Add other features if you have them (e.g., 'Volume', 'Open')
target = 'Price'

# Fix: Ensure the 'Price' column in train_df and test_df is numeric before scaling
# It was reloaded as a CSV in the previous cell, losing the float conversion.
train_df.loc[:, 'Price'] = train_df['Price'].astype(str).str.replace(',', '', regex=False).astype(float)
test_df.loc[:, 'Price'] = test_df['Price'].astype(str).str.replace(',', '', regex=False).astype(float)

# 2. Scale the data (Fit ONLY on train set to prevent data leakage)
scaler = MinMaxScaler(feature_range=(0, 1))
# Fix: Fit scaler on the values array to avoid the feature name warning later
train_scaled = scaler.fit_transform(train_df[features].values)
test_scaled = scaler.transform(test_df[features].values)

# 3. Multi-Horizon Sliding Window Function
def create_multi_horizon_sequences(data, lookback):
    X, y = [], []

    # The + 7 accounts for the 7-day ahead prediction, ensuring enough data points exist
    for i in range(len(data) - lookback - 7):
        X.append(data[i : i + lookback])

        # Collect targets for 1-day, 3-day, and 7-day ahead
        y_1day = data[i + lookback, 0]
        y_3day = data[i + lookback + 2, 0]
        y_7day = data[i + lookback + 6, 0]

        y.append([y_1day, y_3day, y_7day])

    return np.array(X), np.array(y)

# Define lookback window (e.g., use past 60 days)
LOOKBACK = 60

X_train, y_train = create_multi_horizon_sequences(train_scaled, LOOKBACK)
X_test, y_test = create_multi_horizon_sequences(test_scaled, LOOKBACK)

print(f"X_train shape: {X_train.shape}") # Expected: (samples, 60, 1)
print(f"y_train shape: {y_train.shape}") # Expected: (samples, 3)

print(f"X_test shape: {X_test.shape}")   # Expected: (samples, 60, 1)
print(f"y_test shape: {y_test.shape}")    # Expected: (samples, 3)

X_train shape: (3932, 60, 1)
y_train shape: (3932, 3)
X_test shape: (933, 60, 1)
y_test shape: (933, 3)

### 1D CNN MODEL

In [15]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, Flatten, Dense, LeakyReLU, Dropout, Input
from tensorflow.keras.optimizers import Adam

# Define the forecasting horizons
HORIZONS = [1, 3, 7] # For 1-day, 3-day, and 7-day ahead predictions

# --- Model Architecture ---
model_cnn = Sequential([
    Input(shape=(LOOKBACK, X_train.shape[2])), # Explicit Input Layer
    Conv1D(filters=64, kernel_size=3),
    LeakyReLU(negative_slope=0.1),
    Dropout(0.2), # Prevents overfitting

    Conv1D(filters=32, kernel_size=3),
    LeakyReLU(negative_slope=0.1),
    Dropout(0.2),

    Flatten(), # Flattening avoids the loss of temporal data from Global Pooling

    Dense(32),
    LeakyReLU(negative_slope=0.1),

    # Dense output layer must match the number of horizons (3: 1-day, 3-day, 7-day)
    Dense(len(HORIZONS))
])

# --- Compile Model ---
# Using a slightly lower learning rate (0.0005) to keep the gradients stable
model_cnn.compile(
    optimizer=Adam(learning_rate=0.0005),
    loss='mse',
    metrics=['mae']
)

model_cnn.summary()

# --- Train Model ---
print("\n--- Starting Model Training ---")
history = model_cnn.fit(
    X_train, y_train,
    epochs=40,
    batch_size=32,
    validation_split=0.1,  # Uses 10% of training data to check for overfitting
    verbose=1
)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d (Conv1D)                 │ (None, 58, 64)         │           256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ leaky_re_lu (LeakyReLU)         │ (None, 58, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 58, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_1 (Conv1D)               │ (None, 56, 32)         │         6,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ leaky_re_lu_1 (LeakyReLU)       │ (None, 56, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 56, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 1792)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 32)             │        57,376 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ leaky_re_lu_2 (LeakyReLU)       │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 63,907 (249.64 KB)

 Trainable params: 63,907 (249.64 KB)

 Non-trainable params: 0 (0.00 B)

--- Starting Model Training ---
Epoch 1/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 9s 39ms/step - loss: 4.6897e-04 - mae: 0.0107 - val_loss: 0.0116 - val_mae: 0.0741
Epoch 2/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.8228e-04 - mae: 0.0066 - val_loss: 0.0083 - val_mae: 0.0605
Epoch 3/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.5087e-04 - mae: 0.0063 - val_loss: 0.0197 - val_mae: 0.1040
Epoch 4/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.2610e-04 - mae: 0.0058 - val_loss: 0.0144 - val_mae: 0.0807
Epoch 5/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.1742e-04 - mae: 0.0056 - val_loss: 0.0133 - val_mae: 0.0765
Epoch 6/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.0982e-04 - mae: 0.0054 - val_loss: 0.0194 - val_mae: 0.0977
Epoch 7/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0261e-04 - mae: 0.0051 - val_loss: 0.0156 - val_mae: 0.0852
Epoch 8/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9.5803e-05 - mae: 0.0051 - val_loss: 0.0184 - val_mae: 0.0929
Epoch 9/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.9916e-05 - mae: 0.0049 - val_loss: 0.0189 - val_mae: 0.0930
Epoch 10/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.7543e-05 - mae: 0.0050 - val_loss: 0.0249 - val_mae: 0.1135
Epoch 11/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.1237e-05 - mae: 0.0047 - val_loss: 0.0172 - val_mae: 0.0900
Epoch 12/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.5850e-05 - mae: 0.0050 - val_loss: 0.0238 - val_mae: 0.1091
Epoch 13/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1118e-05 - mae: 0.0046 - val_loss: 0.0154 - val_mae: 0.0843
Epoch 14/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7226e-05 - mae: 0.0047 - val_loss: 0.0143 - val_mae: 0.0775
Epoch 15/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.6083e-05 - mae: 0.0042 - val_loss: 0.0097 - val_mae: 0.0607
Epoch 16/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2960e-05 - mae: 0.0042 - val_loss: 0.0128 - val_mae: 0.0747
Epoch 17/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.0303e-05 - mae: 0.0044 - val_loss: 0.0171 - val_mae: 0.0903
Epoch 18/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.7032e-05 - mae: 0.0043 - val_loss: 0.0179 - val_mae: 0.0910
Epoch 19/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2886e-05 - mae: 0.0041 - val_loss: 0.0160 - val_mae: 0.0832
Epoch 20/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5068e-05 - mae: 0.0042 - val_loss: 0.0125 - val_mae: 0.0725
Epoch 21/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.5205e-05 - mae: 0.0044 - val_loss: 0.0136 - val_mae: 0.0742
Epoch 22/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2828e-05 - mae: 0.0041 - val_loss: 0.0183 - val_mae: 0.0951
Epoch 23/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0703e-05 - mae: 0.0041 - val_loss: 0.0141 - val_mae: 0.0787
Epoch 24/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.6594e-05 - mae: 0.0039 - val_loss: 0.0179 - val_mae: 0.0894
Epoch 25/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.0295e-05 - mae: 0.0041 - val_loss: 0.0278 - val_mae: 0.1160
Epoch 26/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0838e-05 - mae: 0.0043 - val_loss: 0.0236 - val_mae: 0.1032
Epoch 27/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1621e-05 - mae: 0.0041 - val_loss: 0.0223 - val_mae: 0.1006
Epoch 28/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.4388e-05 - mae: 0.0039 - val_loss: 0.0266 - val_mae: 0.1087
Epoch 29/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.6735e-05 - mae: 0.0040 - val_loss: 0.0354 - val_mae: 0.1269
Epoch 30/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.4528e-05 - mae: 0.0040 - val_loss: 0.0278 - val_mae: 0.1132
Epoch 31/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.3821e-05 - mae: 0.0040 - val_loss: 0.0296 - val_mae: 0.1139
Epoch 32/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.2726e-05 - mae: 0.0038 - val_loss: 0.0310 - val_mae: 0.1174
Epoch 33/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.1028e-05 - mae: 0.0038 - val_loss: 0.0321 - val_mae: 0.1192
Epoch 34/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.3316e-05 - mae: 0.0039 - val_loss: 0.0359 - val_mae: 0.1133
Epoch 35/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.8638e-05 - mae: 0.0038 - val_loss: 0.0395 - val_mae: 0.1241
Epoch 36/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.8047e-05 - mae: 0.0038 - val_loss: 0.0677 - val_mae: 0.1622
Epoch 37/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.0764e-05 - mae: 0.0039 - val_loss: 0.0430 - val_mae: 0.1354
Epoch 38/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.7076e-05 - mae: 0.0038 - val_loss: 0.0330 - val_mae: 0.1174
Epoch 39/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4.5373e-05 - mae: 0.0036 - val_loss: 0.0485 - val_mae: 0.1458
Epoch 40/40
111/111 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4.8314e-05 - mae: 0.0040 - val_loss: 0.0435 - val_mae: 0.1338

In [16]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

# 1. Predict on test set using the trained model_cnn
# Ensure model_cnn, X_test, y_test, and scaler are defined from previous cells
predictions_scaled = model_cnn.predict(X_test)

# Safe Denormalization Function for Multi-Horizon Targets
def inverse_transform_multi(scaler, scaled_data):
    # Ensure data is numpy array
    scaled_data = np.asarray(scaled_data)

    # Handle both 1D (single horizon) and 2D (multi-horizon) cases for y_test
    if scaled_data.ndim == 1:
        orig_shape = scaled_data.shape
        denorm_flat = scaler.inverse_transform(scaled_data.reshape(-1, 1))
        return denorm_flat.reshape(orig_shape)
    else:
        orig_shape = scaled_data.shape
        # Flatten to a single column, inverse transform, and reshape back
        flat_data = scaled_data.reshape(-1, 1)
        denorm_flat = scaler.inverse_transform(flat_data)
        return denorm_flat.reshape(orig_shape)

predictions_actual = inverse_transform_multi(scaler, predictions_scaled)
y_test_actual = inverse_transform_multi(scaler, y_test)

horizons = ['1-Day Ahead', '3-Day Ahead', '7-Day Ahead']

print("--- Model Evaluation Metrics for CNN ---")

# 3. Loop through columns to evaluate each horizon individually
for i, horizon_name in enumerate(horizons):
    actuals = y_test_actual[:, i]
    preds = predictions_actual[:, i]

    mae = mean_absolute_error(actuals, preds)
    rmse = np.sqrt(mean_squared_error(actuals, preds))

    # Small epsilon added to denominator to prevent division by zero
    mape = np.mean(np.abs((actuals - preds) / (actuals + np.finfo(float).eps))) * 100

    print(f"\n📈 Metrics for {horizon_name}:")
    print(f"  MAE:  ${mae:.2f}")
    print(f"  RMSE: ${rmse:.2f}")
    print(f"  MAPE: {mape:.2f}%")

30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step
--- Model Evaluation Metrics for CNN ---

📈 Metrics for 1-Day Ahead:
  MAE:  $7380.23
  RMSE: $8490.40
  MAPE: 20.86%

📈 Metrics for 3-Day Ahead:
  MAE:  $12626.52
  RMSE: $14550.83
  MAPE: 35.09%

📈 Metrics for 7-Day Ahead:
  MAE:  $16684.03
  RMSE: $19250.34
  MAPE: 45.92%

In [17]:
print(f"Your model is configured for {LOOKBACK} timesteps.")

Your model is configured for 60 timesteps.

# RNN MODEL

In [18]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense, Dropout

# Define the SimpleRNN Architecture
model_rnn = Sequential([
    # First SimpleRNN layer (return_sequences=True to pass sequences to the next layer)
    SimpleRNN(units=64, return_sequences=True, input_shape=(X_train.shape[1], X_train.shape[2])),
    Dropout(0.2),

    # Second SimpleRNN layer (return_sequences=False returns only the final state)
    SimpleRNN(units=32, return_sequences=False),
    Dropout(0.2),

    # Fully connected hidden layer
    Dense(32, activation='relu'),

    # Output layer: 3 units for [1-day, 3-day, 7-day] forecasts
    Dense(3)
])

# Compile the SimpleRNN model
model_rnn.compile(optimizer='adam', loss='mse', metrics=['mae'])
model_rnn.summary()

# Train the SimpleRNN model
history_rnn = model_rnn.fit(
    X_train, y_train,
    epochs=30,
    batch_size=32,
    validation_data=(X_test, y_test),
    verbose=1
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 60, 64)         │         4,224 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 60, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_1 (SimpleRNN)        │ (None, 32)             │         3,104 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 32)             │         1,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 8,483 (33.14 KB)

 Trainable params: 8,483 (33.14 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 11s 40ms/step - loss: 0.0108 - mae: 0.0462 - val_loss: 0.0086 - val_mae: 0.0672
Epoch 2/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0023 - mae: 0.0225 - val_loss: 0.0041 - val_mae: 0.0475
Epoch 3/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0016 - mae: 0.0184 - val_loss: 0.0036 - val_mae: 0.0435
Epoch 4/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0013 - mae: 0.0169 - val_loss: 0.0031 - val_mae: 0.0416
Epoch 5/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0012 - mae: 0.0163 - val_loss: 0.0029 - val_mae: 0.0389
Epoch 6/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0011 - mae: 0.0156 - val_loss: 0.0052 - val_mae: 0.0549
Epoch 7/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 9.0865e-04 - mae: 0.0140 - val_loss: 0.0026 - val_mae: 0.0357
Epoch 8/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0011 - mae: 0.0142 - val_loss: 0.0020 - val_mae: 0.0295
Epoch 9/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 8.5532e-04 - mae: 0.0133 - val_loss: 0.0032 - val_mae: 0.0398
Epoch 10/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 8.3125e-04 - mae: 0.0123 - val_loss: 0.0021 - val_mae: 0.0320
Epoch 11/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.9493e-04 - mae: 0.0129 - val_loss: 0.0025 - val_mae: 0.0382
Epoch 12/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.4719e-04 - mae: 0.0127 - val_loss: 0.0020 - val_mae: 0.0290
Epoch 13/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 8.0539e-04 - mae: 0.0132 - val_loss: 0.0042 - val_mae: 0.0464
Epoch 14/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.6175e-04 - mae: 0.0118 - val_loss: 0.0021 - val_mae: 0.0299
Epoch 15/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.1957e-04 - mae: 0.0114 - val_loss: 0.0019 - val_mae: 0.0287
Epoch 16/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.7754e-04 - mae: 0.0116 - val_loss: 0.0021 - val_mae: 0.0298
Epoch 17/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.8219e-04 - mae: 0.0115 - val_loss: 0.0027 - val_mae: 0.0381
Epoch 18/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4813e-04 - mae: 0.0117 - val_loss: 0.0017 - val_mae: 0.0271
Epoch 19/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.2369e-04 - mae: 0.0118 - val_loss: 0.0023 - val_mae: 0.0356
Epoch 20/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.1375e-04 - mae: 0.0119 - val_loss: 0.0024 - val_mae: 0.0344
Epoch 21/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.5357e-04 - mae: 0.0114 - val_loss: 0.0024 - val_mae: 0.0341
Epoch 22/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.9104e-04 - mae: 0.0111 - val_loss: 0.0043 - val_mae: 0.0482
Epoch 23/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.3837e-04 - mae: 0.0116 - val_loss: 0.0055 - val_mae: 0.0559
Epoch 24/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.9048e-04 - mae: 0.0111 - val_loss: 0.0015 - val_mae: 0.0256
Epoch 25/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.3680e-04 - mae: 0.0110 - val_loss: 0.0014 - val_mae: 0.0246
Epoch 26/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.4513e-04 - mae: 0.0108 - val_loss: 0.0022 - val_mae: 0.0311
Epoch 27/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.5820e-04 - mae: 0.0104 - val_loss: 0.0016 - val_mae: 0.0265
Epoch 28/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.1514e-04 - mae: 0.0108 - val_loss: 0.0014 - val_mae: 0.0266
Epoch 29/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.8937e-04 - mae: 0.0112 - val_loss: 0.0042 - val_mae: 0.0498
Epoch 30/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.5667e-04 - mae: 0.0113 - val_loss: 0.0018 - val_mae: 0.0286

In [19]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error

# 1. Predict on test data using SimpleRNN
predictions_scaled_rnn = model_rnn.predict(X_test)

# 2. Denormalize back to actual Bitcoin prices (USD)
predictions_actual_rnn = scaler.inverse_transform(predictions_scaled_rnn)
y_test_actual = scaler.inverse_transform(y_test)

horizons = ['1-Day Ahead', '3-Day Ahead', '7-Day Ahead']

print("--- Multi-Horizon SimpleRNN Evaluation Metrics ---")

# 3. Calculate metrics loop
for i, horizon_name in enumerate(horizons):
    actuals = y_test_actual[:, i]
    preds = predictions_actual_rnn[:, i]

    mae = mean_absolute_error(actuals, preds)
    rmse = np.sqrt(mean_squared_error(actuals, preds))
    mape = np.mean(np.abs((actuals - preds) / actuals)) * 100

    print(f"\n📊 Metrics for {horizon_name}:")
    print(f"  MAE:  ${mae:.2f}")
    print(f"  RMSE: ${rmse:.2f}")
    print(f"  MAPE: {mape:.2f}%")

30/30 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step
--- Multi-Horizon SimpleRNN Evaluation Metrics ---

📊 Metrics for 1-Day Ahead:
  MAE:  $1483.94
  RMSE: $2201.95
  MAPE: 3.91%

📊 Metrics for 3-Day Ahead:
  MAE:  $1703.09
  RMSE: $2595.64
  MAPE: 4.56%

📊 Metrics for 7-Day Ahead:
  MAE:  $2274.26
  RMSE: $3277.74
  MAPE: 6.67%

## LSTM MODEL

In [20]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

# Define the LSTM Architecture
model_lstm = Sequential([
    # First LSTM layer (return_sequences=True to pass sequences to the next layer)
    LSTM(units=64, return_sequences=True, input_shape=(X_train.shape[1], X_train.shape[2])),
    Dropout(0.2),

    # Second LSTM layer (return_sequences=False returns only the final hidden state)
    LSTM(units=32, return_sequences=False),
    Dropout(0.2),

    # Fully connected hidden layer
    Dense(32, activation='relu'),

    # Output layer: 3 units for [1-day, 3-day, 7-day] forecasts
    Dense(3)
])

# Compile the LSTM model
model_lstm.compile(optimizer='adam', loss='mse', metrics=['mae'])
model_lstm.summary()

# Train the LSTM model
history_lstm = model_lstm.fit(
    X_train, y_train,
    epochs=30,
    batch_size=32,
    validation_data=(X_test, y_test),
    verbose=1
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 60, 64)         │        16,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 60, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         1,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 30,467 (119.01 KB)

 Trainable params: 30,467 (119.01 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 0.0039 - mae: 0.0281 - val_loss: 0.0070 - val_mae: 0.0573
Epoch 2/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0170 - val_loss: 0.0036 - val_mae: 0.0397
Epoch 3/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 9.7224e-04 - mae: 0.0150 - val_loss: 0.0034 - val_mae: 0.0462
Epoch 4/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 8.5891e-04 - mae: 0.0137 - val_loss: 0.0029 - val_mae: 0.0406
Epoch 5/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 8.5023e-04 - mae: 0.0134 - val_loss: 0.0041 - val_mae: 0.0534
Epoch 6/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - loss: 7.9836e-04 - mae: 0.0130 - val_loss: 0.0025 - val_mae: 0.0332
Epoch 7/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 7.9528e-04 - mae: 0.0125 - val_loss: 0.0031 - val_mae: 0.0356
Epoch 8/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.9184e-04 - mae: 0.0122 - val_loss: 0.0021 - val_mae: 0.0326
Epoch 9/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.9136e-04 - mae: 0.0121 - val_loss: 0.0023 - val_mae: 0.0318
Epoch 10/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.8133e-04 - mae: 0.0125 - val_loss: 0.0024 - val_mae: 0.0386
Epoch 11/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 5.6131e-04 - mae: 0.0113 - val_loss: 0.0061 - val_mae: 0.0593
Epoch 12/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 6.7818e-04 - mae: 0.0125 - val_loss: 0.0030 - val_mae: 0.0347
Epoch 13/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.5830e-04 - mae: 0.0112 - val_loss: 0.0038 - val_mae: 0.0393
Epoch 14/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.5817e-04 - mae: 0.0112 - val_loss: 0.0027 - val_mae: 0.0338
Epoch 15/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.2238e-04 - mae: 0.0116 - val_loss: 0.0021 - val_mae: 0.0319
Epoch 16/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.0573e-04 - mae: 0.0114 - val_loss: 0.0022 - val_mae: 0.0364
Epoch 17/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.0891e-04 - mae: 0.0116 - val_loss: 0.0029 - val_mae: 0.0353
Epoch 18/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 5.8981e-04 - mae: 0.0117 - val_loss: 0.0029 - val_mae: 0.0362
Epoch 19/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 6.9222e-04 - mae: 0.0121 - val_loss: 0.0018 - val_mae: 0.0296
Epoch 20/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 5.3447e-04 - mae: 0.0113 - val_loss: 0.0063 - val_mae: 0.0603
Epoch 21/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.4550e-04 - mae: 0.0110 - val_loss: 0.0033 - val_mae: 0.0402
Epoch 22/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.1050e-04 - mae: 0.0122 - val_loss: 0.0026 - val_mae: 0.0331
Epoch 23/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.1543e-04 - mae: 0.0110 - val_loss: 0.0027 - val_mae: 0.0344
Epoch 24/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.5428e-04 - mae: 0.0112 - val_loss: 0.0040 - val_mae: 0.0467
Epoch 25/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 4.7067e-04 - mae: 0.0104 - val_loss: 0.0047 - val_mae: 0.0516
Epoch 26/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.3176e-04 - mae: 0.0112 - val_loss: 0.0018 - val_mae: 0.0303
Epoch 27/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 5.2919e-04 - mae: 0.0108 - val_loss: 0.0028 - val_mae: 0.0341
Epoch 28/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 6.1854e-04 - mae: 0.0119 - val_loss: 0.0018 - val_mae: 0.0276
Epoch 29/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 5.8978e-04 - mae: 0.0113 - val_loss: 0.0058 - val_mae: 0.0562
Epoch 30/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.8103e-04 - mae: 0.0115 - val_loss: 0.0025 - val_mae: 0.0328

In [21]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error

# 1. Predict on test data using LSTM
predictions_scaled_lstm = model_lstm.predict(X_test)

# 2. Denormalize back to actual Bitcoin prices (USD)
predictions_actual_lstm = scaler.inverse_transform(predictions_scaled_lstm)
y_test_actual = scaler.inverse_transform(y_test)

horizons = ['1-Day Ahead', '3-Day Ahead', '7-Day Ahead']

print("--- Multi-Horizon LSTM Evaluation Metrics ---")

# 3. Calculate metrics loop
for i, horizon_name in enumerate(horizons):
    actuals = y_test_actual[:, i]
    preds = predictions_actual_lstm[:, i]

    mae = mean_absolute_error(actuals, preds)
    rmse = np.sqrt(mean_squared_error(actuals, preds))
    mape = np.mean(np.abs((actuals - preds) / actuals)) * 100

    print(f"\n📊 Metrics for {horizon_name}:")
    print(f"  MAE:  ${mae:.2f}")
    print(f"  RMSE: ${rmse:.2f}")
    print(f"  MAPE: {mape:.2f}%")

30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
--- Multi-Horizon LSTM Evaluation Metrics ---

📊 Metrics for 1-Day Ahead:
  MAE:  $1734.00
  RMSE: $2897.53
  MAPE: 4.21%

📊 Metrics for 3-Day Ahead:
  MAE:  $1916.30
  RMSE: $2902.33
  MAPE: 5.31%

📊 Metrics for 7-Day Ahead:
  MAE:  $2603.82
  RMSE: $3686.60
  MAPE: 7.73%

### TRANSFORMER MODEL

In [22]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Dropout, LayerNormalization, MultiHeadAttention, GlobalAveragePooling1D

# 1. Inputs
inputs = Input(shape=(X_train.shape[1], X_train.shape[2]))

# 2. Transformer Encoder Block
# Multi-Head Self-Attention Layer
attention_output = MultiHeadAttention(num_heads=4, key_dim=64)(inputs, inputs)
attention_output = Dropout(0.2)(attention_output)
x1 = LayerNormalization(epsilon=1e-6)(inputs + attention_output)

# Feed-Forward Network Block
ffn = Sequential([
    Dense(64, activation='relu'),
    Dense(X_train.shape[2])
])(x1)
ffn = Dropout(0.2)(ffn)
x2 = LayerNormalization(epsilon=1e-6)(x1 + ffn)

# 3. Pooling and Prediction Head
x = GlobalAveragePooling1D()(x2)
x = Dense(32, activation='relu')(x)
outputs = Dense(3)(x)  # 3 units for [1-day, 3-day, 7-day] forecasts

# Define, Compile, and Summarize Model
model_transformer = Model(inputs=inputs, outputs=outputs)
model_transformer.compile(optimizer='adam', loss='mse', metrics=['mae'])
model_transformer.summary()

# Train the Transformer Model
history_transformer = model_transformer.fit(
    X_train, y_train,
    epochs=30,
    batch_size=32,
    validation_data=(X_test, y_test),
    verbose=1
)

Model: "functional_4"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_3       │ (None, 60, 1)     │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ multi_head_attenti… │ (None, 60, 1)     │      1,793 │ input_layer_3[0]… │
│ (MultiHeadAttentio… │                   │            │ input_layer_3[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_7 (Dropout) │ (None, 60, 1)     │          0 │ multi_head_atten… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add (Add)           │ (None, 60, 1)     │          0 │ input_layer_3[0]… │
│                     │                   │            │ dropout_7[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ layer_normalization │ (None, 60, 1)     │          2 │ add[0][0]         │
│ (LayerNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ sequential_3        │ (None, 60, 1)     │        193 │ layer_normalizat… │
│ (Sequential)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_8 (Dropout) │ (None, 60, 1)     │          0 │ sequential_3[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add_1 (Add)         │ (None, 60, 1)     │          0 │ layer_normalizat… │
│                     │                   │            │ dropout_8[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ layer_normalizatio… │ (None, 60, 1)     │          2 │ add_1[0][0]       │
│ (LayerNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ global_average_poo… │ (None, 1)         │          0 │ layer_normalizat… │
│ (GlobalAveragePool… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_8 (Dense)     │ (None, 32)        │         64 │ global_average_p… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_9 (Dense)     │ (None, 3)         │         99 │ dense_8[0][0]     │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 2,153 (8.41 KB)

 Trainable params: 2,153 (8.41 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 11s 46ms/step - loss: 0.0269 - mae: 0.0844 - val_loss: 0.2517 - val_mae: 0.4581
Epoch 2/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0254 - mae: 0.0943 - val_loss: 0.2463 - val_mae: 0.4522
Epoch 3/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0254 - mae: 0.0947 - val_loss: 0.2457 - val_mae: 0.4515
Epoch 4/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0254 - mae: 0.0943 - val_loss: 0.2432 - val_mae: 0.4487
Epoch 5/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0253 - mae: 0.0953 - val_loss: 0.2515 - val_mae: 0.4579
Epoch 6/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0254 - mae: 0.0938 - val_loss: 0.2431 - val_mae: 0.4487
Epoch 7/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0254 - mae: 0.0949 - val_loss: 0.2459 - val_mae: 0.4518
Epoch 8/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0254 - mae: 0.0951 - val_loss: 0.2469 - val_mae: 0.4528
Epoch 9/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0254 - mae: 0.0951 - val_loss: 0.2522 - val_mae: 0.4586
Epoch 10/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0254 - mae: 0.0942 - val_loss: 0.2454 - val_mae: 0.4513
Epoch 11/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0254 - mae: 0.0945 - val_loss: 0.2444 - val_mae: 0.4501
Epoch 12/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0253 - mae: 0.0951 - val_loss: 0.2488 - val_mae: 0.4549
Epoch 13/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0254 - mae: 0.0943 - val_loss: 0.2467 - val_mae: 0.4526
Epoch 14/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0254 - mae: 0.0947 - val_loss: 0.2466 - val_mae: 0.4525
Epoch 15/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0254 - mae: 0.0948 - val_loss: 0.2477 - val_mae: 0.4538
Epoch 16/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0254 - mae: 0.0954 - val_loss: 0.2505 - val_mae: 0.4568
Epoch 17/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0254 - mae: 0.0943 - val_loss: 0.2502 - val_mae: 0.4564
Epoch 18/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0254 - mae: 0.0947 - val_loss: 0.2479 - val_mae: 0.4540
Epoch 19/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0254 - mae: 0.0950 - val_loss: 0.2486 - val_mae: 0.4547
Epoch 20/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0254 - mae: 0.0944 - val_loss: 0.2479 - val_mae: 0.4540
Epoch 21/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0254 - mae: 0.0947 - val_loss: 0.2486 - val_mae: 0.4548
Epoch 22/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0254 - mae: 0.0946 - val_loss: 0.2460 - val_mae: 0.4519
Epoch 23/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0254 - mae: 0.0948 - val_loss: 0.2471 - val_mae: 0.4531
Epoch 24/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0254 - mae: 0.0947 - val_loss: 0.2451 - val_mae: 0.4509
Epoch 25/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0254 - mae: 0.0945 - val_loss: 0.2465 - val_mae: 0.4524
Epoch 26/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0254 - mae: 0.0953 - val_loss: 0.2471 - val_mae: 0.4531
Epoch 27/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0254 - mae: 0.0945 - val_loss: 0.2479 - val_mae: 0.4540
Epoch 28/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0254 - mae: 0.0949 - val_loss: 0.2503 - val_mae: 0.4566
Epoch 29/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0254 - mae: 0.0941 - val_loss: 0.2447 - val_mae: 0.4504
Epoch 30/30
123/123 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0254 - mae: 0.0953 - val_loss: 0.2497 - val_mae: 0.4560

In [23]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

# 1. Generate predictions using the trained Transformer model
predictions_scaled_trans = model_transformer.predict(X_test)

# 2. Inverse transform back to the original Bitcoin price scale (USD)
predictions_actual_trans = scaler.inverse_transform(predictions_scaled_trans)
y_test_actual = scaler.inverse_transform(y_test)

horizons = ['1-Day Ahead', '3-Day Ahead', '7-Day Ahead']

print("--- Multi-Horizon Transformer Evaluation Metrics ---")

# 3. Calculate and print metrics for each horizon
for i, horizon_name in enumerate(horizons):
    actuals = y_test_actual[:, i]
    preds = predictions_actual_trans[:, i]

    mae = mean_absolute_error(actuals, preds)
    rmse = np.sqrt(mean_squared_error(actuals, preds))
    mape = np.mean(np.abs((actuals - preds) / actuals)) * 100

    print(f"\n🤖 Metrics for {horizon_name}:")
    print(f"  MAE:  ${mae:.2f}")
    print(f"  RMSE: ${rmse:.2f}")
    print(f"  MAPE: {mape:.2f}%")

30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step
--- Multi-Horizon Transformer Evaluation Metrics ---

🤖 Metrics for 1-Day Ahead:
  MAE:  $28962.47
  RMSE: $31708.98
  MAPE: 83.80%

🤖 Metrics for 3-Day Ahead:
  MAE:  $28968.08
  RMSE: $31739.31
  MAPE: 83.71%

🤖 Metrics for 7-Day Ahead:
  MAE:  $28988.57
  RMSE: $31811.35
  MAPE: 83.54%

### DATA VISUALISATION

In [ ]:
import matplotlib.pyplot as plt

# 1. Generate predictions from all four models on the test set
pred_scaled_srnn  = model_rnn.predict(X_test)         # SimpleRNN
pred_scaled_lstm  = model_lstm.predict(X_test)        # LSTM
pred_scaled_cnn   = model_cnn.predict(X_test)         # 1D CNN
pred_scaled_trans = model_transformer.predict(X_test) # Transformer

# 2. Denormalize predictions and ground truth to USD
pred_usd_srnn  = scaler.inverse_transform(pred_scaled_srnn)
pred_usd_lstm  = scaler.inverse_transform(pred_scaled_lstm)
pred_usd_cnn   = scaler.inverse_transform(pred_scaled_cnn)
pred_usd_trans = scaler.inverse_transform(pred_scaled_trans)
y_test_usd     = scaler.inverse_transform(y_test)

horizons = ['1-Day Ahead', '3-Day Ahead', '7-Day Ahead']

# 3. Plot each horizon in a separate subplot
fig, axes = plt.subplots(3, 1, figsize=(14, 18), sharex=False)
fig.suptitle('Bitcoin Price Forecasting: Model Comparison Across Horizons', fontsize=16, fontweight='bold', y=0.92)

for i, horizon_name in enumerate(horizons):
    ax = axes[i]

    # Ground Truth
    ax.plot(y_test_usd[:, i], label='Actual Price', color='black', linewidth=1.8, linestyle='-')

    # Model Predictions
    ax.plot(pred_usd_srnn[:, i],  label='SimpleRNN',   color='darkorange', linewidth=1.2, alpha=0.85)
    ax.plot(pred_usd_lstm[:, i],  label='LSTM',        color='royalblue',  linewidth=1.2, alpha=0.85)
    ax.plot(pred_usd_cnn[:, i],   label='1D CNN',      color='crimson',    linewidth=1.2, alpha=0.85)
    ax.plot(pred_usd_trans[:, i], label='Transformer', color='forestgreen', linewidth=1.2, alpha=0.85)

    ax.set_title(f'Forecasting Horizon: {horizon_name}', fontsize=12, fontweight='bold')
    ax.set_ylabel('Price (USD)', fontsize=10)
    ax.grid(True, linestyle='--', alpha=0.5)
    ax.legend(loc='upper left', fontsize=10)

axes[-1].set_xlabel('Test Data Time Steps (Chronological)', fontsize=11)

plt.tight_layout(rect=[0, 0, 1, 0.90])
plt.show()

30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [ ]:
import numpy as np
import pandas as pd

# 1. Grab the single most recent sequence from your dataset
# Shape needed: (1, timesteps, features)
latest_sequence = X_test[-1:]

# 2. Generate future predictions across models
fut_scaled_srnn  = model_rnn.predict(latest_sequence)
fut_scaled_lstm  = model_lstm.predict(latest_sequence)
fut_scaled_cnn   = model_cnn.predict(latest_sequence)
fut_scaled_trans = model_transformer.predict(latest_sequence)

# 3. Denormalize predictions back to actual USD values
fut_usd_srnn  = scaler.inverse_transform(fut_scaled_srnn)[0]
fut_usd_lstm  = scaler.inverse_transform(fut_scaled_lstm)[0]
fut_usd_cnn   = scaler.inverse_transform(fut_scaled_cnn)[0]
fut_usd_trans = scaler.inverse_transform(fut_scaled_trans)[0]

# 4. Display the forecasted prices side-by-side
forecast_df = pd.DataFrame({
    'Horizon': ['1-Day Ahead', '3-Day Ahead', '7-Day Ahead'],
    'SimpleRNN ($)': np.round(fut_usd_srnn, 2),
    'LSTM ($)': np.round(fut_usd_lstm, 2),
    '1D CNN ($)': np.round(fut_usd_cnn, 2),
    'Transformer ($)': np.round(fut_usd_trans, 2)
})

print("--- Upcoming Multi-Horizon Price Forecast ---")
print(forecast_df.to_string(index=False))

In [ ]:
import numpy as np
import pandas as pd

# 1. Grab the last 60 rows from your feature dataset
# (Replace 'features' with your list of column names, or use df directly if all columns were used)
# Fix: Select only the 'Price' column as the scaler was fitted only on 'Price'
last_60_days_raw = df['Price'].tail(60).values.reshape(-1, 1)

# 2. Scale the 60-day window using your pre-fitted scaler
last_60_days_scaled = scaler.transform(last_60_days_raw)

# 3. Reshape input to (batch_size=1, timesteps=60, features)
X_latest = np.reshape(last_60_days_scaled, (1, 60, last_60_days_scaled.shape[1]))

# 4. Generate predictions across all 4 trained models
scaled_pred_srnn  = model_rnn.predict(X_latest)
scaled_pred_lstm  = model_lstm.predict(X_latest)
scaled_pred_cnn   = model_cnn.predict(X_latest)
scaled_pred_trans = model_transformer.predict(X_latest)

# 5. Denormalize back to actual USD price values
usd_pred_srnn  = scaler.inverse_transform(scaled_pred_srnn)[0]
usd_pred_lstm  = scaler.inverse_transform(scaled_pred_lstm)[0]
usd_pred_cnn   = scaler.inverse_transform(scaled_pred_cnn)[0]
usd_pred_trans = scaler.inverse_transform(scaled_pred_trans)[0]

# 6. Format into a summary table
forecast_60d_df = pd.DataFrame({
    'Horizon': ['1-Day Ahead', '3-Day Ahead', '7-Day Ahead'],
    'SimpleRNN ($)': np.round(usd_pred_srnn, 2),
    'LSTM ($)': np.round(usd_pred_lstm, 2),
    '1D CNN ($)': np.round(usd_pred_cnn, 2),
    'Transformer ($)': np.round(usd_pred_trans, 2)
})

print("--- Forecast Based on the Last 60 Days ---")
print(forecast_60d_df.to_string(index=False))

In [ ]:
import matplotlib.pyplot as plt

# Retrieve historical close prices for the last 60 days
historical_60_days = scaler.inverse_transform(last_60_days_scaled)[:, 0]
last_price = historical_60_days[-1]

# Timesteps alignment
history_timesteps = np.arange(-59, 1)  # -59 to 0
future_timesteps = [1, 3, 7]

plt.figure(figsize=(12, 6))

# Plot recent 60-day price history
plt.plot(history_timesteps, historical_60_days, label='Historical Price (Last 60 Days)', color='black', linewidth=2)

# Plot forecasts starting from the last known price point
plt.plot([0] + future_timesteps, [last_price] + list(usd_pred_srnn),  marker='o', linestyle='--', label='SimpleRNN', color='darkorange')
plt.plot([0] + future_timesteps, [last_price] + list(usd_pred_lstm),  marker='o', linestyle='--', label='LSTM', color='royalblue')
plt.plot([0] + future_timesteps, [last_price] + list(usd_pred_cnn),   marker='o', linestyle='--', label='1D CNN', color='crimson')
plt.plot([0] + future_timesteps, [last_price] + list(usd_pred_trans), marker='o', linestyle='--', label='Transformer', color='forestgreen')

plt.axvline(x=0, color='gray', linestyle=':', label='Current Day (Today)')

plt.title('Bitcoin Price Trajectory: 60-Day History & Multi-Model Forecast', fontsize=14, fontweight='bold')
plt.xlabel('Timeline (Days relative to today)', fontsize=11)
plt.ylabel('Price (USD)', fontsize=11)
plt.grid(True, linestyle='--', alpha=0.5)
plt.legend(loc='upper left')

plt.tight_layout()
plt.show()

In [ ]:
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error

models = {
    'SimpleRNN': pred_usd_srnn,
    'LSTM': pred_usd_lstm,
    '1D CNN': pred_usd_cnn,
    'Transformer': pred_usd_trans
}

# Calculate MAE in USD for each model across horizons
results = []
for name, preds in models.items():
    mae_1d = mean_absolute_error(y_test_usd[:, 0], preds[:, 0])
    mae_3d = mean_absolute_error(y_test_usd[:, 1], preds[:, 1])
    mae_7d = mean_absolute_error(y_test_usd[:, 2], preds[:, 2])
    overall_mae = mean_absolute_error(y_test_usd, preds)

    results.append({
        'Model': name,
        '1-Day MAE ($)': round(mae_1d, 2),
        '3-Day MAE ($)': round(mae_3d, 2),
        '7-Day MAE ($)': round(mae_7d, 2),
        'Overall MAE ($)': round(overall_mae, 2)
    })

# Render comparison table
df_results = pd.DataFrame(results).sort_values(by='Overall MAE ($)')
print(df_results.to_string(index=False))